title: Hi, im Florian.
description: >
  This is my personal blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Florian Haas
author-img: florian-haas.jpg
about-author: I should probably blog more.
social-twitter: xahteiwi
social-github: fghaas
social-linkedin: fghaas
social-email: xahteiwi@gmail.com

gems: [jekyll-paginate]

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
