title: Hi, im Florian.
description: >
  This is my personal blog.
permalink: '/:year-:month-:day/:title.html'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fghaas.github.io"

# Author Settings
author: Florian Haas
author-img: florian-haas.jpg
about-author: These are fairly random ramblings.
social-twitter: xahteiwi
social-github: fghaas
social-linkedin: fghaas
social-keybase: fghaas
social-email: xahteiwi@gmail.com

analytics: UA-114026555-1

gems:
  - jekyll-paginate
  - jekyll-feed

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
